'''
Created on Apr 27, 2015

@author: DHawkins
'''

position = [
 {'abbrev': 'al', 'column': 7, 'row': 7, 'state': 'alabama'},
 {'abbrev': 'ak', 'column': 1, 'row': 8, 'state': 'alaska'},
 {'abbrev': 'az', 'column': 2, 'row': 6, 'state': 'arizona'},
 {'abbrev': 'ar', 'column': 5, 'row': 6, 'state': 'arkansas'},
 {'abbrev': 'ca', 'column': 1, 'row': 5, 'state': 'california'},
 {'abbrev': 'co', 'column': 3, 'row': 5, 'state': 'colorado'},
 {'abbrev': 'ct', 'column': 10, 'row': 3, 'state': 'connecticut'},
 {'abbrev': 'dc', 'column': 9, 'row': 6, 'state': 'district of columbia'},
 {'abbrev': 'de', 'column': 10, 'row': 5, 'state': 'delaware'},
 {'abbrev': 'fl', 'column': 8, 'row': 8, 'state': 'florida'},
 {'abbrev': 'ga', 'column': 8, 'row': 7, 'state': 'georgia'},
 {'abbrev': 'hi', 'column': 2, 'row': 8, 'state': 'hawaii'},
 {'abbrev': 'id', 'column': 2, 'row': 3, 'state': 'idaho'},
 {'abbrev': 'il', 'column': 6, 'row': 4, 'state': 'illinois'},
 {'abbrev': 'in', 'column': 7, 'row': 4, 'state': 'indiana'},
 {'abbrev': 'ia', 'column': 5, 'row': 4, 'state': 'iowa'},
 {'abbrev': 'ks', 'column': 4, 'row': 6, 'state': 'kansas'},
 {'abbrev': 'ky', 'column': 6, 'row': 5, 'state': 'kentucky'},
 {'abbrev': 'la', 'column': 5, 'row': 7, 'state': 'louisiana'},
 {'abbrev': 'me', 'column': 11, 'row': 1, 'state': 'maine'},
 {'abbrev': 'md', 'column': 9, 'row': 5, 'state': 'maryland'},
 {'abbrev': 'ma', 'column': 11, 'row': 2, 'state': 'massachusetts'},
 {'abbrev': 'mi', 'column': 7, 'row': 3, 'state': 'michigan'},
 {'abbrev': 'mn', 'column': 5, 'row': 3, 'state': 'minnesota'},
 {'abbrev': 'ms', 'column': 6, 'row': 7, 'state': 'mississippi'},
 {'abbrev': 'mo', 'column': 5, 'row': 5, 'state': 'missouri'},
 {'abbrev': 'mt', 'column': 3, 'row': 3, 'state': 'montana'},
 {'abbrev': 'ne', 'column': 4, 'row': 5, 'state': 'nebraska'},
 {'abbrev': 'nv', 'column': 2, 'row': 4, 'state': 'nevada'},
 {'abbrev': 'nh', 'column': 10, 'row': 2, 'state': 'new hampshire'},
 {'abbrev': 'nj', 'column': 10, 'row': 4, 'state': 'new jersey'},
 {'abbrev': 'nm', 'column': 3, 'row': 6, 'state': 'new mexico'},
 {'abbrev': 'ny', 'column': 9, 'row': 3, 'state': 'new york'},
 {'abbrev': 'nc', 'column': 7, 'row': 6, 'state': 'north carolina'},
 {'abbrev': 'nd', 'column': 4, 'row': 3, 'state': 'north dakota'},
 {'abbrev': 'oh', 'column': 8, 'row': 4, 'state': 'ohio'},
 {'abbrev': 'ok', 'column': 4, 'row': 7, 'state': 'oklahoma'},
 {'abbrev': 'or', 'column': 1, 'row': 4, 'state': 'oregon'},
 {'abbrev': 'pa', 'column': 9, 'row': 4, 'state': 'pennsylvania'},
 {'abbrev': 'ri', 'column': 11, 'row': 3, 'state': 'rhode island'},
 {'abbrev': 'sc', 'column': 8, 'row': 6, 'state': 'south carolina'},
 {'abbrev': 'sd', 'column': 4, 'row': 4, 'state': 'south dakota'},
 {'abbrev': 'tn', 'column': 6, 'row': 6, 'state': 'tennessee'},
 {'abbrev': 'tx', 'column': 4, 'row': 8, 'state': 'texas'},
 {'abbrev': 'ut', 'column': 2, 'row': 5, 'state': 'utah'},
 {'abbrev': 'vt', 'column': 9, 'row': 2, 'state': 'vermont'},
 {'abbrev': 'va', 'column': 8, 'row': 5, 'state': 'virginia'},
 {'abbrev': 'wa', 'column': 1, 'row': 3, 'state': 'washington'},
 {'abbrev': 'wv', 'column': 7, 'row': 5, 'state': 'west virginia'},
 {'abbrev': 'wi', 'column': 6, 'row': 3, 'state': 'wisconsin'},
 {'abbrev': 'wy', 'column': 3, 'row': 4, 'state': 'wyoming'}
 ]